### ISSUE TITLE
Manual PATH assignment to runtime

### ISSUE THREAD

**Issue by arknable** [nanovms/ops-intellij#9] opened 2021-06-16 22:59 UTC
@eyberg has qemu installed and included in PATH but somehow Java runtime does not recognize it

**Comment by eyberg** [comment] 2021-06-16 23:00
dupe of https://github.com/nanovms/ops-intellij/issues/8

**Comment by arknable** [comment] 2021-06-16 23:00
close as duplication

**Closed as completed** 2021-06-16 23:01 UTC
